FROM maven:3.9-eclipse-temurin-17 AS build

WORKDIR /app

COPY pom.xml .
COPY src ./src
COPY .mvn ./.mvn
COPY mvnw .

RUN mvn clean package -DskipTests

FROM eclipse-temurin:17-jre

WORKDIR /app

# Директория для логов конфликтов
RUN mkdir -p /app/logs

COPY --from=build /app/target/IS_LAB1-0.0.1-SNAPSHOT.war app.war

EXPOSE 8080

ENTRYPOINT ["java", "-jar", "app.war"]

